### ISSUE TITLE
Naas - Update librairy pyarrow.HadoopFileSystem

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#108]
![image](https://user-images.githubusercontent.com/48032461/121135979-63e97c00-c835-11eb-8a5d-e7dbefb64ca7.png)

**Comment by Dr0p42** [comment]
Ok, so this warning is not coming from us but from Papermill. We are already using the last version of Papermilll so we cannot fix this by upgrading versions. Looking at a way to temporarily suppress this warning.

**Comment by jravenel** [comment]
@Dr0p42 got new feedback from a user that this is seen as a bug.

**Comment by jravenel** [comment]
fixed.
