### ISSUE TITLE
Naas - Jobs can not get job runs with Jupyter drivers

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#116]
import requests
from os import environ

jup_token = environ.get('JUPYTERHUB_API_TOKEN')
headers = {"Authorization": f"token {jup_token}"}
url = f'https://app.naas.ai/user/bob@cashstory.com/proxy/5000/job'
res = requests.get(url, headers=headers)

data = res.json()
for job in data:
    status = job.get("status")
    path = job.get("path")
    if path == "admin_naas/usage/script/update_credits_spent.ipynb":
        print(job)

**Comment by Dr0p42** [comment]
@FlorentLvr @jravenel you can test this by running:
```python
import requests
from os import environ

jup_token = environ.get('JUPYTERHUB_API_TOKEN')
headers = {"Authorization": f"token {jup_token}"}
url = f'http://127.0.0.1:5000/job'
res = requests.get(url, headers=headers)

data = res.json()
data
```

in preproduction. (You can run it on my machine if you want I imported jobs from Bob.)

---

![image](https://user-images.githubusercontent.com/22365519/121537372-2850dc80-ca04-11eb-9513-737338ce3892.png)
