### ISSUE TITLE
Naas - As a user I want that naas and naas-driver force update even if I tried to run `pip install naas{-drivers} --user`

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/naas#122]
Today we have an issue when user are running:
`pip install --user naas`
`pip install --user naas-drivers`

This is pulling and installing `naas` and/or `naas-drivers` in `/home/ftp/.local/lib/python3.8/site-packages` which takes over `/opt/conda/lib/python3.8/site-packages` (where we install new `naas` and `naas-drivers` versions).

We should run `rm -rf /home/ftp/.local/lib/python3.8/site-packages/naas*` to make sure the user is always using latest versions.

**Comment by jravenel** [comment]
For me, this should be covered by https://docs.naas.ai/advanced/updates#in-naas-cloud
I'm closing.
@Dr0p42 feel free to reopen if needed.
