### ISSUE TITLE
Awesome-notebook - Open in Naas : Download working but notebook not open

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#129]

**Comment by Dr0p42** [comment]
@FlorentLvr @QuentinKlebaur can you test that it is working properly please ? Just click on the link:

http://app.dev.naas.ai/user-redirect/naas/downloader?url=https://raw.githubusercontent.com/jupyter-naas/awesome-notebooks/master/LinkedIn/LinkedIn_Get_posts_stats_from_profile.ipynb

**Comment by QuentinKlebaur** [comment]
> @FlorentLvr @QuentinKlebaur can you test that it is working properly please ? Just click on the link:
> 
> http://app.dev.naas.ai/user-redirect/naas/downloader?url=https://raw.githubusercontent.com/jupyter-naas/awesome-notebooks/master/LinkedIn/LinkedIn_Get_posts_stats_from_profile.ipynb

Nope, that's not open the file by default
