### ISSUE TITLE
JupyterLab restart when down.

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#136]
Sometimes, in a non-linear manner, we can see crashes inside our Kubernetes/AWS cloud infra.

It's an issue related to Kubernetes spawner that does not create deployment but just a pod.

What we should expect is an immediate reboot of the machine anytime it crashes. #chaosstrategy

**Comment by jravenel** [comment]
Creation of the crash handler microservice to get a restart if the server crashed. Not yet opensource.
