### ISSUE TITLE
Naas manager - Rework of the design

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#146]
- Make a nice naas manager logo/header, when I click on manager, it refreshes the page 
- Put search in full width
- Add in headers: docs, roadmap, upgrade, open server, create notebook
- Create a nice footer with social media
- Prepare a Profile page "(coming soon)"
- Prepare a Account statement page "(coming soon)"
- Reorder the columns in the table

**Comment by jravenel** [comment]
Rest to be done : 
- Create new template notebook when click on “+ new”
- Add CRISP dans manager et l’enlever de Jupyter
- Load Templates from Github 
    - Add Last update
    - Add Creator
    - Add Action (try if multiple action button can be done like “Open in Naas”, “See on Youtube”, “Download in HTML” 
    - Visualize “Value” as text when scheduler
- Visualize templates from modal in manager before usage

**Comment by jravenel** [comment]
Update (todo) 
- Create new template notebook when click on “+ new” ==> OK
- Add CRISP dans manager et l’enlever de Jupyter ==> PENDING
- Load Templates from Github 
    - Add Last update ==> LATER
    - Add Creator ==> LATER
    - Add Action (try if multiple action button can be done like “Open in Naas”, “See on Youtube”, “Download in HTML” ==> OK
    - Visualize “Value” as text when scheduler ==> LATER
- Visualize templates from modal in manager before usage ==> LATER
- History : column Date => delete milliseconds ==> TODO
- Column status (à appliquer partout): ==> TODO
    - Healthy = ✅ Active
    - Error = ❌ Error
    - Started = 🎽 Running
    - Edited = ✏️Edited 
- Search slow==> TODO
- When I click on the file in manager it opens into the Jupyter tab==> TODO

@QuentinKlebaur  :)

**Comment by jravenel** [comment]
fixed.
