### ISSUE TITLE
Naas manager - Create refresh button 

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#171]
align right with tabs "Templates" / "Tasks" / "History" 
use logo refresh : https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFile%3AIc_refresh_48px.svg&psig=AOvVaw0uE3Wviv0xiGI0QohblaMK&ust=1627721777116000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJD56Ka2ivICFQAAAAAdAAAAABAJ

**Comment by FlorentLvr** [comment]
@QuentinKlebaur, est-ce que tu pourrais revoir le design du boutton pour qu'il soit vert comme le "+ New"

![image](https://user-images.githubusercontent.com/48032461/127357282-e71fe6df-e2ad-4161-898d-fc14eaeea0cb.png)

**Comment by QuentinKlebaur** [comment]
![tmp](https://user-images.githubusercontent.com/45666866/127612148-2f6cd53d-ec1d-4799-ae3b-b952e1b09eee.png)

Here the new design, what do think about ?

**Comment by QuentinKlebaur** [comment]
![Capture d’écran de 2021-08-02 09-11-04](https://user-images.githubusercontent.com/45666866/127819199-217c1b40-99a3-4039-8ef1-0d223f017907.png)

**Comment by jravenel** [comment]
done a long time ago but not closed.
