### ISSUE TITLE
Naas manager - Tasks: rename "Service" with capitalize letter

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#172]

**Comment by FlorentLvr** [comment]
@QuentinKlebaur, l'évolution ne semble pas avoir été effectuée :

![image](https://user-images.githubusercontent.com/48032461/127357474-325d8a1d-bd05-44a2-a4b4-747c12e80131.png)

**Comment by FlorentLvr** [comment]
@QuentinKlebaur , dans l'onglet "History", la modification n'a pas été effectué non plus et il faudrait renommer la colonne "Service" pour être aligné avec l'onglet "Tasks"

![image](https://user-images.githubusercontent.com/48032461/127358374-4e9c827c-df77-41b6-a749-01b3bae6f978.png)

**Comment by jravenel** [comment]
fixed a long time ago but not closed.
