### ISSUE TITLE
Naas manager - Account balance: Rework message

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#176]
Title : Account Balance is coming soon...

Message : In the meantime, please 
<a href="mailto:hello@naas.ai?subject=STATEMENT&body=STATEMENT">send message 📧</a> to get your account statement.

We will send it to you ASAP 🙏.

**Comment by QuentinKlebaur** [comment]
![Capture d’écran de 2021-07-30 14-02-59](https://user-images.githubusercontent.com/45666866/127650319-ffb3a668-ffae-4db5-af82-55926024d5c0.png)
@FlorentLvr

**Comment by jravenel** [comment]
now available.
