### ISSUE TITLE
Change the red buttons in Naas like "Restart" to green #32d973

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#180]
In the current setups, some red buttons are counter-intuitive, "red" color = danger normally but here it applies to actions that will bring the user to a better state (restart kernel, clear workspace....), it should be following our green #32d973 in my opinion. 

Below the "restart" but it also applies to "clear workspace"
<img width="500" alt="Screenshot 2021-07-29 at 10 21 25" src="https://user-images.githubusercontent.com/21052349/127458093-3bd4fa0c-3db1-4671-aa29-680b92142127.png">

**Comment by FlorentLvr** [comment]
@jravenel , as discussed today, restarting a kernel is considered as critical actions hence the reason why the button is red
