### ISSUE TITLE
Fix - naas manager history `busy` state are weird.

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/naas#182]
Today we have a very strange behavior where a notebook (in fact webhook) have multiple state:
- `running` (Change to `started`?)
- `busy`
- `Active` (Change to `completed`?)
- `Error`

If you take a look at this screenshot, all the rows are in fact referring to a single execution.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/22365519/127626317-9ae2fd09-04f8-472f-a82e-75218cc9fd97.png">

The issue is that all the `busy` rows have a different `ID` and a different `type`.

The `type` should be kept, so here `notebook` and the `ID` should be kept as well, here `8dfe`.

**Comment by jravenel** [comment]
fixed a long time ago but not closed.
