### ISSUE TITLE
Naas manager - History : Error message not displayed on click on "Error" status

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#194]
![image](https://user-images.githubusercontent.com/48032461/127972291-6cf9ca4c-422a-46d6-b101-cddd112c6007.png)

**Comment by jravenel** [comment]
@FlorentLvr does this mean you want to put back the popup we add before?

**Comment by jravenel** [comment]
@QuentinKlebaur I don't know if you have done it but it does not work for me.
