### ISSUE TITLE
Improve Manager UX - 1.22

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#199]
- double message en account balance
https://files.slack.com/files-pri/T6US3QP4L-F02A040MDB8/screenshot_2021-08-04_at_19.06.08.png
- send message in account balance do no do anything => add "...to hello@naas.ai to get your..." as a plan B if it does not work to send direct email.
- Change "Account balance" to "Account" 
- ✅ Completed et ✅ Active ca devrait pas avoir le mm icon, c’est confusing => 👌Completed
- ✅ Sent et ✅ Completed dans History idem => 👌 Completed
- Delete phantom icon when refresh and center the circle
https://files.slack.com/files-pri/T6US3QP4L-F029S59US23/screenshot_2021-08-04_at_19.09.01.png
- when I click on “Refresh I expect the refresh of a table and not all the manager
https://files.slack.com/files-pri/T6US3QP4L-F029S5N14K1/screenshot_2021-08-04_at_19.11.34.png
- Refresh button should be secondary button like in website 
https://files.slack.com/files-pri/T6US3QP4L-F02A73WHN59/screenshot_2021-08-04_at_19.16.17.png

**Comment by jravenel** [comment]
@QuentinKlebaur here are my feedbacks following 1.21.3

**Comment by FlorentLvr** [comment]
@tparente-ui : 
- "✅ Completed" must be changed to "👌 Completed"
- "✅ Sent" must be changed to "📩 Sent"

**Comment by jravenel** [comment]
All has been done with @tparente-ui to send to app.dev.naas.ai 
@FlorentLvr can you check once the bump version bump: version 1.22.0b3 → 1.22.0b4. 
https://github.com/jupyter-naas/naas/actions 

@Dr0p42 FYI
