### ISSUE TITLE
Naas run - Do not add naas.run() as webhook task in naas manager

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#201]
![image](https://user-images.githubusercontent.com/48032461/128472507-6b74de5f-db88-4e32-8900-dc35106e059f.png)

Behaviour expected :
- Add notebook in task manager with a different name (_run.ipynb)
- Run notebook (with webhook feature)
- Get output when failed
- Delete webhook in task manager

**Comment by jravenel** [comment]
@Dr0p42 @FlorentLvr as discussed I removed @tparente-ui from this task: too deep.

**Comment by jravenel** [comment]
Looking at the code, it seems an enhancement to me.

**Comment by Dr0p42** [comment]
Ok I took a look at this issue, it seems indeed that when there is an error occurring when doing a `naas.run()`, the task is not removed.

<img width="1117" alt="Screenshot 2021-08-25 at 12 02 02" src="https://user-images.githubusercontent.com/22365519/130771124-b9c95925-201e-44c3-bd81-2f0519c6d078.png">

_history_

<img width="1111" alt="Screenshot 2021-08-25 at 12 05 09" src="https://user-images.githubusercontent.com/22365519/130771362-303b3f28-f495-46a4-9d80-a4597d270084.png">

We can see that on `error` the `task` is kept.

Used notebook:

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/22365519/130771580-0c1febda-99a2-41b7-959b-e3317b7e0777.png">

**Comment by jravenel** [comment]
After discussion, there is the straightforward solution to that. At one point we will need to refactor this feature and therefore, we are putting it back to the Backlog.

**Comment by jravenel** [comment]
Fixed.
