### ISSUE TITLE
Naas manager - History : Error message not displayed

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#202]
When I tried to call a webhook or run scheduler, I didn't see the result in naas manager tab "History" if an error occured. 

![image](https://user-images.githubusercontent.com/48032461/128682570-90ef6d51-d786-463f-9dd7-b5ba2e0204a4.png)

The error is displayed in naas manager tab "Tasks"
![image](https://user-images.githubusercontent.com/48032461/128682614-31b27b42-dd0f-4810-b13a-6049291de96c.png)

Test:
Webhook and scheduler

**Comment by jravenel** [comment]
After investigation, only @FlorentLvr cannot see this line in his app.dev.naas.ai account. It should not be considered as bug but we need to monitor it after launch of the version 1.22.0b4
