### ISSUE TITLE
Naas manager - History : "Error" status not displayed

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#205]
- florent.ravenel@cashstory.com 
- bob@cashstory.com 
- thomas.parenteau@epitech.eu (dev)

Tasks : 

![image](https://user-images.githubusercontent.com/48032461/129533316-91c19941-47c4-4cfc-a4f9-f637be9aa74d.png)

History : 

![image](https://user-images.githubusercontent.com/48032461/129533256-f1fe6f77-0e1d-4003-875c-0215ebd2c48b.png)

**Comment by jravenel** [comment]
As discussed today @Dr0p42, we have the error but it's a problem of insert in DB. We need to fix and sanitize the log management in the same PR.
