### ISSUE TITLE
Add a symbolic link to access the production folder

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#208]
As a user, I want to access the production folder from my file directory.

**Comment by jravenel** [comment]
- Validate design du folder '🎩_Production' == '⚙️_Production' ==  '🚀_Production' ==  '🦚_Production' == '🐉_Production' == '🐲_Production' == '⚡️_Production' 
**Winner**: '⚡️Production' => @Dr0p42 
- Write notebook readme => @Dr0p42 @jravenel

**Comment by Dr0p42** [comment]
@jravenel We need to sync to work around a File/Notebook to put in the production folder. This one should provide warning / best practices about what user should and should not do in the production directory.

**Comment by FlorentLvr** [comment]
@Dr0p42 , I got this message when I imported naas : 
![image](https://user-images.githubusercontent.com/48032461/131466774-5a64ac84-7afd-4dee-b8bf-4bfa84771728.png)

**Comment by jravenel** [comment]
Winner is "⚡️ → Production"
