### ISSUE TITLE
Identify users types from JupyterHub SQL DB

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#219]
Input : 
- email 
- type of account (Naas Free, Naas Starter, Naas Pro, Naas Enterprise, Naas Core Team, Naas Admin) 

→ Update JupyterHub SQL DB
→ Get data to allocate servers

**Comment by FlorentLvr** [comment]
Once user is created, naas plan "NAAS_FREE" is affected by default. So we need to have the possibility to update Naas plan directly in JupyterHub SQL DB.

Plus, find a way to add new fields in user info table with "REGISTER_DATE".
Make sure, we can get it from "https://app.naas.ai/hub/signup"

**Comment by jravenel** [comment]
Pending: go live with history @FlorentLvr to update (validate: list of users, code of plan)

**Comment by jravenel** [comment]
Create account types : 
Pro_child → child account for Pro
Enterprise_child → child account for Pro
with metadata on "contract number" on user
