### ISSUE TITLE
Allocate dedicated server from user types

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#220]
From user types stored in JupyterHub DB, Naas admin can allocate a dedicated server in terms of : 
- CPU 
- RAM

**Comment by FlorentLvr** [comment]
First, find a way to allocate dedicated server for one user or several users manually.

**Comment by jravenel** [comment]
Guarantee → Free: 300Mo, Starter: 500Mo, Pro: 750Mo, Enterprise: 8Go

Guarantee: minimum requirement allocated to your Jupyter Server.

**Comment by jravenel** [comment]
Pending question check if we can assing multiple user to same machine requirement @Dr0p42
