### ISSUE TITLE
Naas Notification: HTTP 500 Error when sending notifications from local install, binder 

### ISSUE THREAD

**Issue by aiexplorations** [jupyter-naas/naas#229]
1. Notification API - `naas.notification.send()` does not work properly when using naas on local install
2. Notification API - `naas.notification.send()` does not work properly when using naas on binder 

**Note**: Notification API - `naas.notification.send()` works properly when using naas on cloud using Google SSO login

Attachments: Binder run and Local run for notification example

![image](https://user-images.githubusercontent.com/10044506/135113785-8c6bec10-5cb0-4eaa-9218-0ba0b411d4d0.png)
![image](https://user-images.githubusercontent.com/10044506/135114720-68c9079d-5772-4bf8-93b9-fe3d4dce2ea1.png)

**Comment by jravenel** [comment]
Hi @aiexplorations, thanks a lot. 
We will try to reproduce and let you know our findings. 

Thanks.

**Comment by riderx** [comment]
@aiexplorations email services are not configured in binder, and cannot be without compromise email server security.
For localhost, it can be done if you run the email service and setup email provider.
It's not documented, but you can find the machine your should run there : https://github.com/jupyter-naas/notifications

**Comment by jravenel** [comment]
> @aiexplorations email services are not configured in binder, and cannot be without compromise email server security. For localhost, it can be done if you run the email service and setup email provider. It's not documented, but you can find the machine your should run there : https://github.com/jupyter-naas/notifications

@riderx thanks for your inputs  👍
@aiexplorations happy to help if you need guidance.
