### ISSUE TITLE
Unable to log into Naas from Github SSO

### ISSUE THREAD

**Issue by aiexplorations** [jupyter-naas/naas#230]
"Internal server error" when using Github to perform SSO and log into [naas.ai](https://www.naas.ai/free-forever).

**Comment by jravenel** [comment]
@aiexplorations thanks a lot. We will try to reproduce. 

What's is the browser you use?

**Comment by justin-prather** [comment]
I also have this issue

**Comment by jravenel** [comment]
@Dr0p42 @justin-prather @aiexplorations we have found the source of the problem. It is because your email is not set as public in Github profile. 
You should do it to fix. 
@Dr0p42 will add a fallback message to inform future users about this case. 

FYI @FlorentLvr @Valpiquard
