### ISSUE TITLE
As a user from other Jupyter managed instances I can use naas.scheduler like an API.

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#238]
Feedback from various users.

(Google cloud/colab/deepnote)

**Comment by jravenel** [comment]
@Dr0p42 it's the notebook API project correct?

**Comment by Dr0p42** [comment]
> @Dr0p42 it's the notebook API project correct?

Yes that is one of the targeted use cases :)

**Comment by jravenel** [comment]
duplicate https://github.com/jupyter-naas/naas/issues/286
