### ISSUE TITLE
Access to my account even if I don’t have credits 

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#314]
**Problem**: 
Today when I don't have any more credits, the access to my account is blocked. 
I would like to access my account even if I don't have credits to use: notebook uptime and still get access to my file system.

**Solution**: 
- Add a condition: get credit balance before papermill execution (Naas runner) + statut “🛑 **Out of credits**” in Events tab
- Desactivate the moment when we unauthorize access to the server

**Comment by jravenel** [comment]
@Dr0p42 can the update here 😊?(following our conversation on slack)

**Comment by Dr0p42** [comment]
It is still in progress, I will open a pull request when it's ready on my side 👍

**Comment by Dr0p42** [comment]
@FlorentLvr can you disable your automation blocking users when they reach 0 credits please?

**Comment by FlorentLvr** [comment]
> @FlorentLvr can you disable your automation blocking users when they reach 0 credits please?

It's done :)
