### ISSUE TITLE
Make Naas readme is 100% compliant to standards

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#326]
We need to make sure : 
- buttons previouly added are here
- contributing goes to docs.naas.ai
- install locallly goes to. docs.naas.ai

**Comment by jravenel** [comment]
@chicken-biryani has been working on : 
- install locally 
- get involved / contributing

has been done Gitbook → @jravenel need to check how to get the notifications/workflow right.

**Comment by jravenel** [comment]
Hi @chicken-biryani ,

I reviewed the change request in GitBook and made a few adjustment mainly on : 
- ordering of chapters 
- naming of chapters 
- deleted other contribution path 
- changed the way the form submission was presented to become member 

Well done.  
Next time we need to split issues in smaller chunks to focus on specific parts (naas manager, security)

🤙 Thanks for the good work.

**Comment by jravenel** [comment]
Merged on [docs.naas.ai](https://docs.naas.ai/) @chicken-biryani @Dr0p42 @FlorentLv
![Uploading Screenshot 2022-07-31 at 16.16.55.png…]()

**Comment by chicken-biryani** [comment]
Great! Thank you so much. I'll add the links to the Readme so that we can close this issue.

**Comment by jravenel** [comment]
Perfect let's close this first step :)
