### ISSUE TITLE
Installation of Jupyter-dash do no work.

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#327]
Even via Naas proxy, we cannot manage to launch a dashboard.

**Comment by jravenel** [comment]
@Dr0p42 can you investigate why it's still in "Loading..."?
@eliasdabbas suggested https://dash.plotly.com/app-lifecycle to do so.

**Comment by Dr0p42** [comment]
Hello @jravenel check this out: https://www.loom.com/share/65a0a56d6b99431981245da82f3f6cf3 

You can find the notebook here 👉 [dash-try-install(1).ipynb.zip](https://github.com/jupyter-naas/naas/files/9158388/dash-try-install.1.ipynb.zip)

**Comment by jravenel** [comment]
Thanks @Dr0p42 I confirm it works for me. 
<img width="1346" alt="Screenshot 2022-07-21 at 13 47 15" src="https://user-images.githubusercontent.com/21052349/180206421-07c44237-80ce-4b7b-836c-648818073f75.png">

Some question : 
- do you know why it says the environment is "production", it's misleading with the text below "This is a development server. Do not use it in a production deployment." 
- if we use the scheduler to update data and send to production, is there any impact we should think of?

**Comment by jravenel** [comment]
Other thing @Dr0p42, can we install by default: 
!pip install dash   
!pip install dash-html-components                                         
!pip install dash-core-components                                     
!pip install plotly 
?

**Comment by eliasdabbas** [comment]
@Dr0p42 
> do you know why it says the environment is "production", it's misleading with the text below "This is a development server. Do not use it in a production deployment."

Dash is built using Flask as the server/backend. This message is from Flask. When deploying it's better to use a specialized WSGI and not use the default one. 

Yet, for our purposes, when people are creating apps for simple data analysis, sharing with colleagues, or with a small audience, it shouldn't be a problem. This server is running a simple process so I think it should be fine.
Hope this makes sense.

**Comment by eliasdabbas** [comment]
@jravenel 
> Other thing @Dr0p42, can we install by default: !pip install dash !pip install dash-html-components !pip install dash-core-components !pip install plotly ?

Installing dash alone should install the others with `pip install dash`.
 
In Dash>=2.0.0 `dash_core_components` and `dash_html_components` are no longer separate packages and can be imported from within Dash: 

`from dash import Dash, html, dcc`

It would be great if we can resolve the `JupyterDash` issue also

**Comment by jravenel** [comment]
Thanks for the upadte @eliasdabbas what are you refering too when talking about `JupyterDash` issue?

**Comment by eliasdabbas** [comment]
> Thanks for the update @eliasdabbas what are you refering too when talking about `JupyterDash` issue?

Dash is the package for creating dashboards, and JupyterDash is Dash within notebooks. So the app can appear, right under the code cell, on a separate tab within the notebook, or in a separate window, like in regular Dash. 

Something like this: 

<img width="1193" alt="Screen Shot 2022-07-22 at 9 25 47 PM" src="https://user-images.githubusercontent.com/15708966/180501084-8840bc4c-c0ca-470f-966a-920d04adcbb2.png">

I thought it would be important as this is all about notebooks. It can wait, but it would be great if we have it supported.

**Comment by jravenel** [comment]
next step is to create: 
- a folder called "jupyter-dash" 
- a template using the very simple example we discussed about

**Comment by jravenel** [comment]
This is now closed and awesome-notebooks has been done: https://github.com/jupyter-naas/awesome-notebooks/pull/1128
