### ISSUE TITLE
Naas - CI/CD : Deploying version is not working

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#331]
Here is the error: https://github.com/jupyter-naas/naas/actions/runs/2747161586

**Comment by Dr0p42** [comment]
CI/CD is fixed, I had to loosen requests version requirements.

Here is the action: https://github.com/jupyter-naas/drivers/runs/7648735724?check_suite_focus=true

**Comment by jravenel** [comment]
Ok @Dr0p42 seems all green now, I'm pushing to done in the roadmap
