### ISSUE TITLE
"⚡ Get started with Naas" still visible after update account to Naas folder rename

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#360]
Maybe there is a typo somewhere but the folder is not removed when I update my naas. 

![Image](https://user-images.githubusercontent.com/21052349/200323232-ce0f4714-39ad-4dbc-92fa-15dc52a9e008.png)

**Comment by Dr0p42** [comment]
This issue is resolved by https://github.com/jupyter-naas/naas/commit/f07b3984d1b01f6e2167bed5796a8a2af9d60ec6
