### ISSUE TITLE
Define the naas v2 project architecture

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#379]
Work with Maxime to create a clear project architecture that can help marketers and developers on how to understand and user the project.

Strategy should be define here: https://www.notion.so/naas-official/Tech-Operations-9dd8d01559ab43d283a069be8f78b0e6?pvs=4

Operations should be done in a global repo on Github

**Comment by jravenel** [comment]
To migrated on the future docusaurus repo

**Comment by Dr0p42** [comment]
Should we plan a working session for this one @jravenel ?

**Comment by jravenel** [comment]
Yes let's do it @Dr0p42 can you drop me an invite for a doc session?

**Comment by Dr0p42** [comment]
Hey @jravenel what are the next steps for this one?
