### ISSUE TITLE
Naas last version not working - Conflict with pydantic version

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/naas#440]
We can't use the last version of naas (Version: 2.14.7) because of a conflict with pydantic with naas-python library.
Could you please try to fix it?

![Image](https://github.com/jupyter-naas/naas/assets/48032461/4b7e02a7-a599-4c4b-8e8a-bb20a36af135)

**Comment by FlorentLvr** [comment]
As hotfix, I downgraded the pydantic version in my server but I have some conflicts


![Image](https://github.com/jupyter-naas/naas/assets/48032461/11975aa8-8020-4ccb-ba83-65cd6146eda7)

**Comment by Dr0p42** [comment]
Hey @FlorentLvr, I did a lot of iteration and it seems that it's ok now. Can you validate on your side as well please? By starting a new lab.

Let me know how it goes.

**Comment by FlorentLvr** [comment]
> Hey @FlorentLvr, I did a lot of iteration and it seems that it's ok now. Can you validate on your side as well please? By starting a new lab.
> 
> Let me know how it goes.

I tested it on 2 accounts and it worked! TY
