### ISSUE TITLE
feat: improve Naas readme

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#78]
Community support
Contributing guide
Features
Quick start
Mission

Inspired by 
https://github.com/airbytehq/airbyte/

**Comment by Dr0p42** [comment]
Is this issue related to this commit ? https://github.com/jupyter-naas/naas/commit/7a7570784b2393512e6d8d68babdbc6746519a64 

@jravenel

**Comment by chicken-biryani** [comment]
Hello, @jravenel here's rough work. https://hackmd.io/@9w-awoLYS8-TWvM6lvxy1A/SkX2504ec

I have added a few things. A suggestion-- Can the Installation be put in an 'Installation guide' document and linked? This may make the ReadMe a little light in weight. Too much information can be overwhelming.

**Comment by jravenel** [comment]
Hey @chicken-biryani yes that's a good idea. I really like your proposal.

**Comment by chicken-biryani** [comment]
@jravenel is it okay if I edit it a little more. Come up with a proper draft and then create a PR?

**Comment by jravenel** [comment]
Of course! Let's do this @chicken-biryani

**Comment by jravenel** [comment]
Hey @chicken-biryani let me know if I can help to move forward on this :)

**Comment by chicken-biryani** [comment]
@jravenel we're taking inspiration from airbyte itself, right? Any other suggested places?

I was thinking of improving the conplete readme and then creating a PR instead of one by one.

Is that a good idea?

**Comment by jravenel** [comment]
> @jravenel we're taking inspiration from airbyte itself, right? Any other suggested places?
> 
> I was thinking of improving the conplete readme and then creating a PR instead of one by one.
> 
> Is that a good idea?

Not sure @chicken-biryani , it's always better to split in small chunks to see progress IMHO. Otherwise it's hard to review.
Yes airbyte is the source of inspiration :)

**Comment by Dr0p42** [comment]
Hello @chicken-biryani, were you able to make progress on this issue?
