### ISSUE TITLE
pip install prophet --user : not working

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#85]
When I try to use prophet lib I have an error : Building wheel for prophet (setup.py) ... error
ERROR: Command errored out with exit status 1:

ModuleNotFoundError: No module named 'convertdate'

ERROR: Failed building wheel for prophet
=> as per as the error I tried to install convertdate but it does no do anything. 
Here the script I'm trying to replicate in naas.
https://towardsdatascience.com/time-series-analysis-and-climate-change-7bb4371021e

**Comment by yaswanthkumargothi** [comment]
It seems `pip install convertdate` need to be done before `pip install fbprophet` as `convertdate` is a build dependency. The issue https://github.com/facebook/prophet/issues/1598#issue-666018143  seems a 4 year old issue https://github.com/facebook/prophet/issues/401#issue-285574029, still they don't have a cleaner solution for build fails. 

You can refer to this advice https://github.com/facebook/prophet/issues/1598#issuecomment-665953117 from `fbprophet` developer to install all the build dependencies before installing `fbprophet`.

**Comment by jravenel** [comment]
Thanks a lot @yaswanthkumargothi we will check it out.

**Comment by jravenel** [comment]
we will use prophet via Pycaret
