### ISSUE TITLE
Naas run - Error "❌ Cannot get your file None"

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#86]
When use the naas.run to test a notebook in prod but it returned an error message instead of outputs.

![image](https://user-images.githubusercontent.com/48032461/128471648-ce987b85-ffdf-4d08-99ef-01c00e7dd278.png)

https://public.naas.ai/ZmxvcmVudC0yRXJhdmVuZWwtNDBjYXNoc3RvcnktMkVjb20=/asset/2fe80da9e44cf1bf34e641ad534f4238616af4c76a533500c6b2ef2ebdbc

https://naas.canny.io/incident-report/p/naas-run-error-cannot-get-your-file-none

**Comment by jravenel** [comment]
@tparente-ui @FlorentLvr as discussed, let's document what has been done during the bug fixing session last friday.

**Comment by tparente-ui** [comment]
With Quentin we tried to reproduce the error locally, from there new errors appeared

![unknown (2)](https://user-images.githubusercontent.com/71703095/128675503-61d0ae0a-57bc-447b-b111-ccd86a361ccc.png)

As shown on the screenshots, after launching nass.run a Not_found.txt file is created and indicates an error like this: « File not found at path /home/ftp/.naas/home/ftp/naas/output__Untitled.ipynb »

When you run the naas run again after that, another error occurs, the program does not overwrite the other file from the previous error and reports a "file already exist".

![unknown (3)](https://user-images.githubusercontent.com/71703095/128675524-2732cd4c-547c-4141-9073-89726fdce04f.png)

The naas.run is the call of a webhook, after adding it in the task we execute it with a get request then we try it in the code, if it fits in the exception the output is done and removes the task, which is not the case.

Despite an error in the request, a 200 response is displayed.
The output is therefore impossible to generate.

**Comment by jravenel** [comment]
@Dr0p42 @FlorentLvr as discussed I removed @tparente-ui from this task : too deep.

**Comment by jravenel** [comment]
Seems fixed by the recent updates. 
I cannot reproduce the bug.
<img width="875" alt="Screenshot 2021-08-13 at 12 11 22" src="https://user-images.githubusercontent.com/21052349/129341897-188be1b2-ed10-42f5-aa36-81fbff9c538b.png">
