### ISSUE TITLE
Disable the popup "Welcome Tour" on Naas

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#95]
Multiple popup stack up and come back as of today when opening notebooks, impacting the UX

Might be linked to Jupyter single user

**Comment by jravenel** [comment]
still KO for me. Is it in dev? @QuentinKlebaur

**Comment by jravenel** [comment]
<img width="1680" alt="Screenshot 2021-08-04 at 19 27 54" src="https://user-images.githubusercontent.com/21052349/128226744-930fb6ab-17ab-4eb9-8386-2c06b49394b0.png">
Still KO for me in prod @QuentinKlebaur @tparente-ui to be checked tx

**Comment by QuentinKlebaur** [comment]
As discussed we are going to disable it totally

**Comment by jravenel** [comment]
@Dr0p42 do you have any idea where the deactivation should be done? Is it on naas repository? At first sight it is not in this repository. I think it may be in single user config.

**Comment by jravenel** [comment]
@tparente-ui as discussed this morning with @Dr0p42 , it's possible it is in the project https://github.com/jupyter-naas/awesome-notebooks/issues/168

**Comment by tparente-ui** [comment]
HI ! I've just done a PR on this issue, this last one is not linked on the good repo, you can find the link to the PR here
https://github.com/jupyter-naas/singleuser/pull/38
